[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npx webpack --mode production"]

[start]
cmd = "npx serve -s build -l $PORT"
