[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --omit=dev --no-audit --no-fund"]

[phases.build]
cmds = ["npm install --only=dev", "npm run build"]

[start]
cmd = "npx serve -s build -l $PORT"
